#helm install --name dev-ingresscontroller stable/nginx-ingress --namespace dev
#特别注意，ingress的命名空间必须与它反向代理的service所处的命名空间一致。

### backend service https needs annotations  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
### create secret cmd: kubectl create secret tls forticloud-two-container-secret --key star_forticloud_com-privkey.key  --cert star_forticloud_com-chained.crt  -n sandboxdev
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - k8dashboard.forticloud.com
      secretName: forticloud-dashboard-secret
  rules:
    - host: k8dashboard.forticloud.com
      http:
        paths:
          - path: /
            backend:
              serviceName: dashboard-kubernetes-dashboard
              servicePort: 443

---

# if use the ca certificated crt, the browser will work,
# if not, the browser will block this, but use the curl command gonna work with -k param.
#test case
#curl -vL --resolve ping.k8.com:443:172.16.97.173 https://ping.k8.com/ping
#curl -kvL --resolve ping.k8.com:443:172.16.97.173 https://ping.k8.com/ping

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ping-ingress
  namespace: sandboxdev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - ping.k8.com
      secretName: two-container-secret
  rules:
    - host: ping.k8.com
      http:
        paths:
          - path: /
            backend:
              serviceName: two-container
              servicePort: 80

### How to create secret
# openssl req -newkey rsa:2048 -nodes -keyout server.key -x509 -days 365 -out server.crt
# kubectl create secret tls dashboard-ingress-secret --key server.key  --cert server.crt  -n kube-system

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - k8dashboard.forticloud.com
      secretName: dashboard-ingress-secret
  rules:
    - host: k8dashboard.forticloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
