scrape_configs:
  - job_name: portal
    scrape_interval: 5s
    static_configs:
      - targets: [172.16.93.*:8089]
  - job_name: europe_mrgsrv_container
    scrape_interval: 5s
    static_configs:
      - targets: [172.16.94.*:8089]
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 172.16.*.*:9093
rule_files:
  - /etc/prometheus/*.rules
